version: '3.8'

services:
  php_training_bus:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: php_training_bus
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9000

  nginx_bus:
    image: nginx:latest
    container_name: nginx_training_bus
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/TrainingBusWeb/public/:/app/apps/TrainingBusWeb/public
    depends_on:
      - php_training_bus
