roll:
    path: /roll
    controller: TrainingBusWeb\Controller\RollDiceController::roll

saveRoll:
    path: /save-roll/{roll}
    controller: TrainingBusWeb\Controller\RollDiceController::saveRoll

sendInvite:
    path: /invite/{email}
    controller: TrainingBusWeb\Controller\SendInviteController::sendInvite
